import { User, Case, Prisoner, Alert } from './types';

// 7 Police + 7 Prosecutors + Team Leader + Admin
export const MOCK_USERS: User[] = [
  // Police Users (7 stations)
  { id: 'u1', email: 'officer.jalmeda@example.com', name: 'ጃል ሜዳ ፖሊስ', role: 'police', station: 'station-1', maxCases: 50 },
  { id: 'u2', email: 'officer.aratkilo@example.com', name: 'አራት ኪሎ ፖሊስ', role: 'police', station: 'station-2', maxCases: 50 },
  { id: 'u3', email: 'officer.piyasa@example.com', name: 'ፒያሳ ፖሊስ', role: 'police', station: 'station-3', maxCases: 50 },
  { id: 'u4', email: 'officer.rasdesta@example.com', name: 'ራስ ደስታ ፖሊስ', role: 'police', station: 'station-4', maxCases: 50 },
  { id: 'u5', email: 'officer.atkilt@example.com', name: 'አትክልት ጠራ ፖሊስ', role: 'police', station: 'station-5', maxCases: 50 },
  { id: 'u6', email: 'officer.memraya@example.com', name: 'ሜምርያ ፖሊስ', role: 'police', station: 'station-6', maxCases: 50 },
  { id: 'u7', email: 'officer.qebena@example.com', name: 'ቀበና ፖሊስ', role: 'police', station: 'station-7', maxCases: 50 },
  
  // Prosecutor Users (7 prosecutors with specializations)
  { id: 'p1', email: 'fikadu@example.com', name: 'ፍቃዱ አለማየሁ', role: 'prosecutor', prosecutorId: 'PROS-01', specialization: 'የፀጥታ ወንጀሎች', maxCases: 25 },
  { id: 'p2', email: 'minista@example.com', name: 'ሚኒስታ ጌታቸው', role: 'prosecutor', prosecutorId: 'PROS-02', specialization: 'ስርቆት', maxCases: 25 },
  { id: 'p3', email: 'adisu@example.com', name: 'አዲሱ ኃይለሚካኤል', role: 'prosecutor', prosecutorId: 'PROS-03', specialization: 'ቅማሸት', maxCases: 25 },
  { id: 'p4', email: 'samson@example.com', name: 'ሳምሶን ተስፋዬ', role: 'prosecutor', prosecutorId: 'PROS-04', specialization: 'አደንዛዥ ወንጀሎች', maxCases: 25 },
  { id: 'p5', email: 'wendwesen@example.com', name: 'ወንድወሰን ደምሴ', role: 'prosecutor', prosecutorId: 'PROS-05', specialization: 'የኮምፒውተር ወንጀሎች', maxCases: 25 },
  { id: 'p6', email: 'birhan@example.com', name: 'ብርሃን እሸቱ', role: 'prosecutor', prosecutorId: 'PROS-06', specialization: 'የቤት የሕግ ጉዳዮች', maxCases: 25 },
  { id: 'p7', email: 'amha@example.com', name: 'አምሃ ተካልኝ', role: 'prosecutor', prosecutorId: 'PROS-07', specialization: 'ጥቃት', maxCases: 25 },
  
  // Team Leader
  { id: 'tl1', email: 'teamleader@example.com', name: 'የቡድን መሪ', role: 'teamleader', maxCases: 10 },
  
  // Admin
  { id: 'admin1', email: 'admin@example.com', name: 'አስተዳዳሪ', role: 'admin', maxCases: 5 },
];

// Mock Cases
export const MOCK_CASES: Case[] = [
  {
    id: 'c1',
    caseNumber: 'C-2024-PS01-001',
    suspectName: 'አብርሃም ተሰማ',
    suspectAge: 28,
    suspectGender: 'ወንጀለኛ',
    crimeType: 'ግድያ',
    crimeDescription: 'በማኅበራዊ መንገድ ላይ ግጭት ተፈጥሮ ግድያ ተፈጽሟል',
    crimeLevel: 'ከባድ',
    station: 'station-1',
    policeOfficer: 'ጃል ሜዳ ፖሊስ',
    arrestDate: '2024-03-10',
    status: 'ወደ ዐቃቤ ህግ ተላከ',
    sentToProsecutionDate: '2024-03-12',
    currentStep: 3,
    assignedProsecutorId: 'PROS-01',
    assignedProsecutorName: 'ፍቃዱ አለማየሁ',
    custodyType: 'RTD',
    article38Deadline: '2024-03-26',
    prisonerId: 'PRN-2024-PS01-001',
    createdAt: '2024-03-10',
    updatedAt: '2024-03-12',
    createdBy: 'u1',
    history: [
      { date: '2024-03-10', action: 'ጉዳይ ተፈጥሮዋል', user: 'ጃል ሜዳ ፖሊስ', details: 'ጉዳይ ተፈጥሮዋል' },
      { date: '2024-03-11', action: 'ተጠናቀቀ', user: 'ጃል ሜዳ ፖሊስ', details: 'ምርመራ ተጠናቀቀ' },
      { date: '2024-03-12', action: 'ወደ ዐቃቤ ህግ ተላከ', user: 'ጃል ሜዳ ፖሊስ', details: 'ወደ ዐቃቤ ህግ ተላከ' },
    ],
  },
  {
    id: 'c2',
    caseNumber: 'C-2024-PS01-002',
    suspectName: 'ሚካኤል ደምሴ',
    suspectAge: 35,
    suspectGender: 'ወንጀለኛ',
    crimeType: 'ስርቆት',
    crimeDescription: 'በመንግሥት ህንፃ ውስጥ ስርቆት ተፈጽሟል',
    crimeLevel: 'አማካይ',
    station: 'station-1',
    policeOfficer: 'ጃል ሜዳ ፖሊስ',
    arrestDate: '2024-03-08',
    status: 'መርማራ',
    currentStep: 3,
    assignedProsecutorId: 'PROS-02',
    assignedProsecutorName: 'ሚኒስታ ጌታቸው',
    custodyType: 'TOB',
    prisonerId: 'PRN-2024-PS01-002',
    createdAt: '2024-03-08',
    updatedAt: '2024-03-09',
    createdBy: 'u1',
    history: [
      { date: '2024-03-08', action: 'ጉዳይ ተፈጥሮዋል', user: 'ጃል ሜዳ ፖሊስ', details: 'ጉዳይ ተፈጥሮዋል' },
    ],
  },
  {
    id: 'c3',
    caseNumber: 'C-2024-PS02-001',
    suspectName: 'ደስታ አለሙ',
    suspectAge: 22,
    suspectGender: 'ወንጀለኛምላክ',
    crimeType: 'አደንዛዥ',
    crimeDescription: 'አደንዛዥ ድጎማ ተያይዟል',
    crimeLevel: 'ከባድ',
    station: 'station-2',
    policeOfficer: 'አራት ኪሎ ፖሊስ',
    arrestDate: '2024-03-14',
    status: 'ወደ ዐቃቤ ህግ ተላከ',
    sentToProsecutionDate: '2024-03-15',
    currentStep: 2,
    assignedProsecutorId: 'PROS-04',
    assignedProsecutorName: 'ሳምሶን ተስፋዬ',
    custodyType: 'RTD',
    article38Deadline: '2024-03-28',
    prisonerId: 'PRN-2024-PS02-001',
    createdAt: '2024-03-14',
    updatedAt: '2024-03-15',
    createdBy: 'u2',
    history: [
      { date: '2024-03-14', action: 'ጉዳይ ተፈጥሮዋል', user: 'አራት ኪሎ ፖሊስ', details: 'ጉዳይ ተፈጥሮዋል' },
    ],
  },
  {
    id: 'c4',
    caseNumber: 'C-2024-PS03-001',
    suspectName: 'ነጋሽ ብርሃኔ',
    suspectAge: 42,
    suspectGender: 'ወንጀለኛ',
    crimeType: 'ቅማሸት',
    crimeDescription: 'ሰዎችን በማጭበርበር ገንዘብ ተወስዷል',
    crimeLevel: 'ከባድ',
    station: 'station-3',
    policeOfficer: 'ፒያሳ ፖሊስ',
    arrestDate: '2024-03-05',
    status: 'አንቀጽ 38',
    currentStep: 4,
    assignedProsecutorId: 'PROS-03',
    assignedProsecutorName: 'አዲሱ ኃይለሚካኤል',
    custodyType: 'TOB',
    article38Date: '2024-03-18',
    article38Deadline: '2024-04-01',
    article38Reason: 'ማስረጃ በቂ አይደለም',
    prisonerId: 'PRN-2024-PS03-001',
    createdAt: '2024-03-05',
    updatedAt: '2024-03-18',
    createdBy: 'u3',
    history: [],
  },
  {
    id: 'c5',
    caseNumber: 'C-2024-PS04-001',
    suspectName: 'ኃይለማርያም ገብረእግዚአብሔር',
    suspectAge: 30,
    suspectGender: 'ወንጀለኛ',
    crimeType: 'ስንቅ',
    crimeDescription: 'በሰላም ማስከበር ላይ ስንቅ ተፈጽሟል',
    crimeLevel: 'ከባድ',
    station: 'station-4',
    policeOfficer: 'ራስ ደስታ ፖሊስ',
    arrestDate: '2024-03-12',
    status: 'ወደ ፍርድ ቤት',
    currentStep: 5,
    assignedProsecutorId: 'PROS-01',
    assignedProsecutorName: 'ፍቃዱ አለማየሁ',
    custodyType: 'RTD',
    courtDate: '2024-03-20',
    prisonerId: 'PRN-2024-PS04-001',
    createdAt: '2024-03-12',
    updatedAt: '2024-03-19',
    createdBy: 'u4',
    history: [],
  },
  {
    id: 'c6',
    caseNumber: 'C-2024-PS05-001',
    suspectName: 'ታሚራ አድማሱ',
    suspectAge: 25,
    suspectGender: 'ወንጀለኛምላክ',
    crimeType: 'ሞገስ',
    crimeDescription: 'ባልደረባዋን በእጅ ጉዳት አድርሷል',
    crimeLevel: 'ቀላል',
    station: 'station-5',
    policeOfficer: 'አትክልት ጠራ ፖሊስ',
    arrestDate: '2024-03-15',
    status: 'ዲዳ',
    currentStep: 1,
    custodyType: 'TOB',
    createdAt: '2024-03-15',
    updatedAt: '2024-03-15',
    createdBy: 'u5',
    history: [],
  },
];

// Mock Prisoners
export const MOCK_PRISONERS: Prisoner[] = [
  {
    id: 'pr1',
    prisonerId: 'PRN-2024-PS01-001',
    fullName: 'አብርሃም ተሰማ',
    alias: 'አባቶ',
    gender: 'ወንጀለኛ',
    age: 28,
    arrestDate: '2024-03-10',
    arrestingStation: 'station-1',
    detentionFacility: 'አዲስ አበባ የቁጥጥር ቤት',
    cellNumber: 'B3-12',
    healthNotes: 'የስኳር በሽታ ተጋለጠዋል - መድሃኒት ይደርስለት',
    status: 'IN_CUSTODY',
    relatedCaseId: 'c1',
    createdBy: 'u1',
    createdAt: '2024-03-10',
    visitors: [
      { date: '2024-03-12', visitorName: 'ማርያም ወርቅ', relation: 'ሚስት', notes: 'መድሃኒት አምጥታለች' },
      { date: '2024-03-14', visitorName: 'አባል አለሙ', relation: 'ወንድም', notes: '' },
    ],
  },
  {
    id: 'pr2',
    prisonerId: 'PRN-2024-PS01-002',
    fullName: 'ሚካኤል ደምሴ',
    gender: 'ወንጀለኛ',
    age: 35,
    arrestDate: '2024-03-08',
    arrestingStation: 'station-1',
    detentionFacility: 'አዲስ አበባ የቁጥጥር ቤት',
    cellNumber: 'A2-05',
    status: 'IN_CUSTODY',
    relatedCaseId: 'c2',
    createdBy: 'u1',
    createdAt: '2024-03-08',
    visitors: [],
  },
  {
    id: 'pr3',
    prisonerId: 'PRN-2024-PS02-001',
    fullName: 'ደስታ አለሙ',
    alias: 'ደስታ',
    gender: 'ወንጀለኛምላክ',
    age: 22,
    arrestDate: '2024-03-14',
    arrestingStation: 'station-2',
    detentionFacility: 'አዲስ አበባ የቁጥጥር ቤት',
    cellNumber: 'C1-08',
    healthNotes: 'ጤናማ',
    status: 'IN_CUSTODY',
    relatedCaseId: 'c3',
    createdBy: 'u2',
    createdAt: '2024-03-14',
    visitors: [
      { date: '2024-03-15', visitorName: 'ኃይሉ ገብረሚካኤል', relation: 'አባት', notes: 'የሕግ አማካሪ ጠይቋል' },
    ],
  },
  {
    id: 'pr4',
    prisonerId: 'PRN-2024-PS03-001',
    fullName: 'ነጋሽ ብርሃኔ',
    gender: 'ወንጀለኛ',
    age: 42,
    arrestDate: '2024-03-05',
    arrestingStation: 'station-3',
    detentionFacility: 'አዲስ አበባ የቁጥጥር ቤት',
    cellNumber: 'B1-03',
    status: 'IN_CUSTODY',
    relatedCaseId: 'c4',
    createdBy: 'u3',
    createdAt: '2024-03-05',
    visitors: [],
  },
  {
    id: 'pr5',
    prisonerId: 'PRN-2024-PS04-001',
    fullName: 'ኃይለማርያም ገብረእግዚአብሔር',
    gender: 'ወንጀለኛ',
    age: 30,
    arrestDate: '2024-03-12',
    arrestingStation: 'station-4',
    detentionFacility: 'አዲስ አበባ የቁጥጥር ቤት',
    cellNumber: 'A3-11',
    healthNotes: 'የደም ግፊት ተጋለጠዋል',
    status: 'IN_CUSTODY',
    relatedCaseId: 'c5',
    createdBy: 'u4',
    createdAt: '2024-03-12',
    visitors: [],
  },
  {
    id: 'pr6',
    prisonerId: 'PRN-2024-PS05-001',
    fullName: 'ካሳሁን አለሙ',
    alias: 'ካሳ',
    gender: 'ወንጀለኛ',
    age: 27,
    arrestDate: '2024-03-13',
    arrestingStation: 'station-5',
    detentionFacility: 'አዲስ አበባ የቁጥጥር ቤት',
    cellNumber: 'C2-04',
    status: 'IN_CUSTODY',
    relatedCaseId: undefined, // No case filed yet!
    createdBy: 'u5',
    createdAt: '2024-03-13',
    visitors: [],
  },
  {
    id: 'pr7',
    prisonerId: 'PRN-2024-PS05-002',
    fullName: 'ሰለሞን ደምሴ',
    gender: 'ወንጀለኛ',
    age: 31,
    arrestDate: '2024-03-11',
    arrestingStation: 'station-5',
    detentionFacility: 'አዲስ አበባ የቁጥጥር ቤት',
    cellNumber: 'B2-07',
    status: 'IN_CUSTODY',
    relatedCaseId: undefined, // No case filed yet!
    createdBy: 'u5',
    createdAt: '2024-03-11',
    visitors: [],
  },
  {
    id: 'pr8',
    prisonerId: 'PRN-2024-PS06-001',
    fullName: 'ዮሐንስ ገብረሚካኤል',
    gender: 'ወንጀለኛ',
    age: 45,
    arrestDate: '2024-03-01',
    arrestingStation: 'station-6',
    detentionFacility: 'አዲስ አበባ የቁጥጥር ቤት',
    cellNumber: 'A1-02',
    status: 'RELEASED',
    relatedCaseId: undefined,
    releaseDate: '2024-03-10',
    releaseReason: 'ማስረጃ በቂ አልተገኘም',
    createdBy: 'u6',
    createdAt: '2024-03-01',
    visitors: [],
  },
];

// Mock Alerts
export const MOCK_ALERTS: Alert[] = [
  {
    id: 'a1',
    type: 'urgent',
    title: 'RTD ጉዳይ በጊዜያዊ መቆየት',
    message: 'አብርሃም ተሰማ (C-2024-PS01-001) በቁጥጥር ቤት ከ14 ቀናት በላይ ነው',
    relatedCaseId: 'c1',
    relatedPrisonerId: 'PRN-2024-PS01-001',
    createdAt: '2024-03-15',
    isRead: false,
  },
  {
    id: 'a2',
    type: 'warning',
    title: 'ጉዳይ የሌለው እስር ተገኝቷል',
    message: 'ካሳሁን አለሙ ከ7 ቀናት በላይ ነው ጉዳይ የሌለው በቁጥጥር ቤት ውስጥ ነው',
    relatedPrisonerId: 'PRN-2024-PS05-001',
    createdAt: '2024-03-15',
    isRead: false,
  },
  {
    id: 'a3',
    type: 'warning',
    title: 'ጉዳይ የሌለው እስር ተገኝቷል',
    message: 'ሰለሞን ደምሴ ከ7 ቀናት በላይ ነው ጉዳይ የሌለው በቁጥጥር ቤት ውስጥ ነው',
    relatedPrisonerId: 'PRN-2024-PS05-002',
    createdAt: '2024-03-15',
    isRead: false,
  },
  {
    id: 'a4',
    type: 'info',
    title: 'አዲስ ጉዳይ ተላከ',
    message: 'ደስታ አለሙ ጉዳይ ወደ ዐቃቤ ህግ ተላከ',
    relatedCaseId: 'c3',
    createdAt: '2024-03-15',
    isRead: true,
  },
  {
    id: 'a5',
    type: 'urgent',
    title: 'የጤና ስጋት',
    message: 'አብርሃም ተሰማ የስኳር በሽታ ተጋለጠዋል - ቀናት እየገፉ ነው',
    relatedPrisonerId: 'PRN-2024-PS01-001',
    createdAt: '2024-03-15',
    isRead: false,
  },
];
